# Generated by Django 4.1.3 on 2024-07-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentappointment',
            name='department',
        ),
        migrations.AddField(
            model_name='departmentappointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departmentlist', verbose_name='Department List'),
            preserve_default=False,
        ),
    ]
