# Generated by Django 5.0.7 on 2024-07-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departmentappointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentappointment',
            name='user',
        ),
    ]
