# Generated by Django 5.0.7 on 2024-08-01 16:27

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.custom_upload_to)),
                ('content', models.TextField()),
                ('article', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comments', models.ManyToManyField(related_name='blog_post_comments', to=settings.AUTH_USER_MODEL)),
                ('user_published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_user_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posts',
            },
        ),
    ]
