# Generated by Django 5.0.7 on 2024-08-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(related_name='blog_post_comments', to='blog.blogcomment'),
        ),
    ]
