# Generated by Django 4.1.3 on 2024-08-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
