# Generated by Django 4.1.3 on 2024-08-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_postblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='comments',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.postblog'),
            preserve_default=False,
        ),
    ]
