# Generated by Django 5.0.7 on 2024-08-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_blogcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.postblog'),
            preserve_default=False,
        ),
    ]
