# Generated by Django 5.0.7 on 2024-08-02 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_blogcomment_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.postblog', verbose_name='Relation Post'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment User'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='article',
            field=models.CharField(max_length=400, verbose_name='Article post'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='content',
            field=models.TextField(verbose_name='Content post'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title post'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
    ]
